import 'package:decimal/decimal.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

import '../domain/models/entitlement_cache.dart';
import '../domain/models/leg.dart';
import '../domain/models/rule_profile_data.dart';
import '../domain/models/rule_profile_version_data.dart';
import '../domain/models/share_lot.dart';
import '../domain/models/snapshot.dart';
import '../domain/models/underlying.dart';
import '../domain/models/user_preferences.dart';
import '../domain/models/wheel_cycle.dart';

part 'wheel_repository.freezed.dart';

/// Storage-agnostic persistence contract for the whole §3 domain. Both
/// `DriftWheelRepository` and `InMemoryWheelRepository` implement every
/// method here identically in observable behavior (docs/conventions.md §6)
/// — see `test/data/wheel_repository_contract_test.dart` for the shared
/// parity suite that proves it.
///
/// No Drift types, no SQL, no file paths appear in any signature here.
/// Every method is domain-intent named and returns a `Future`, even where
/// an implementation (`InMemoryWheelRepository`) could resolve synchronously.
///
/// IDs for newly-created rows are generated by the repository itself (never
/// by the caller) so state-layer code never has to invent or import a UUID
/// generator — see the Assumption Log in
/// docs/plans/wheel-triage-plan.md for this and other Decide-and-Log calls
/// made while building this interface, including three methods
/// (`getUnderlying`, `getLatestSnapshotForLeg`, `openNextLeg`) added beyond
/// the plan's enumerated minimum because Phases 4/5 have no other way to
/// resolve a leg's ticker, its current snapshot, or to open a covered call
/// on an already-`holdingShares` cycle without misusing `recordRoll`.
abstract class WheelRepository {
  // --- Underlying ---------------------------------------------------

  /// Returns the existing [Underlying] for [ticker] (case-sensitive, as
  /// typed), or creates and returns a new one if none exists yet.
  Future<Underlying> getOrCreateUnderlying(String ticker);

  /// Looks up an [Underlying] by id. Returns `null` if it does not exist.
  Future<Underlying?> getUnderlying(String id);

  // --- RuleProfile ----------------------------------------------------

  /// All seeded/user rule profiles — identity only (`id`, `name`); each
  /// profile's threshold values live on its version rows (Iteration 5,
  /// D-3). Three built-in profiles are seeded at migration time (Feature
  /// Invariant 8).
  Future<List<RuleProfileData>> getRuleProfiles();

  /// Looks up a single rule profile's identity by id. Returns `null` if it
  /// does not exist. For the threshold values a leg was classified under,
  /// look up its pinned version via [getRuleProfileVersion] instead.
  Future<RuleProfileData?> getRuleProfile(String id);

  /// Every version of [profileId], ascending by the integer `version` —
  /// the append-only edit history (D-3/D-11). Ordering is by `version`,
  /// never `effectiveAt`, so two versions saved in the same millisecond
  /// still order deterministically. Empty for an unknown [profileId].
  Future<List<RuleProfileVersionData>> getRuleProfileVersions(String profileId);

  /// Looks up one threshold version by its id (`<profileId>-v<n>`, D-3) —
  /// how a leg's pinned `ruleProfileVersionId` resolves. Returns `null` if
  /// it does not exist (a dangling pin degrades to the built-in defaults at
  /// the caller, D-7).
  Future<RuleProfileVersionData?> getRuleProfileVersion(String versionId);

  /// Appends a new immutable threshold version for [profileId] and returns
  /// it. The id (`<profileId>-v<version>`) and the 1-based [version] are
  /// derived by the repository from the profile's existing versions —
  /// callers never invent either, so the `(profileId, version)` unique key
  /// can never be contradicted by a caller (D-3). One atomic write. There
  /// is deliberately no update or delete counterpart on this interface:
  /// version rows are append-only, and the missing methods are the
  /// structural guard (Feature Invariant 3). Throws [ArgumentError] if no
  /// profile with [profileId] exists.
  Future<RuleProfileVersionData> appendRuleProfileVersion({
    required String profileId,
    required DateTime effectiveAt,
    required NewRuleProfileVersionInput values,
  });

  // --- WheelCycle / Leg lifecycle --------------------------------------

  /// Atomically creates a new [WheelCycle] (`status = sellingPuts`) on
  /// [underlyingId] together with its first [Leg] (`sequence = 0`). One
  /// write from the caller's point of view.
  Future<({WheelCycle cycle, Leg leg})> createCycle({
    required String underlyingId,
    required NewLegInput firstLeg,
  });

  /// Opens a new leg on an EXISTING cycle that is not a roll of another
  /// leg — e.g. the covered call opened right after a put assignment
  /// (§5.4 step 4), or a second covered call opened after the first was
  /// closed early while the cycle is still `holdingShares` (Feature
  /// Invariant 16). `sequence` is assigned by the repository as one more
  /// than the highest existing sequence for [cycleId]; `rolledFromLegId`
  /// is always null for a leg opened this way (contrast with
  /// [recordRoll]'s `newLeg`, which does set it).
  Future<Leg> openNextLeg({
    required String cycleId,
    required NewLegInput leg,
  });

  /// Every leg across every cycle that is not yet closed
  /// (`closedAt == null`).
  Future<List<Leg>> getOpenLegs();

  /// Every leg across every cycle, open and closed, ordered by `openedAt`
  /// ascending with `sequence` as the tie-break (S-216) — the read path for
  /// views that need the whole book rather than only the open legs
  /// [getOpenLegs] returns. The tie-break matters: two legs on different
  /// cycles can be opened in the same millisecond, and callers that render
  /// legs in list order must see the same order from both implementations.
  Future<List<Leg>> getAllLegs();

  /// Looks up a single leg by id. Returns `null` if it does not exist.
  Future<Leg?> getLeg(String id);

  /// All legs belonging to [cycleId], ordered by `sequence` ascending —
  /// the roll chain, in order.
  Future<List<Leg>> getLegsForCycle(String cycleId);

  /// Looks up a single cycle by id. Returns `null` if it does not exist.
  Future<WheelCycle?> getCycle(String id);

  /// Every cycle with `status == closed`, ordered newest-`endedAt`-first
  /// (Phase 15/S-096) — the journal screen's read path. Returns cycles
  /// only, never pre-aggregated totals: a caller that needs per-leg
  /// figures (e.g. contract-weighted P&L, Feature Invariant 25) calls
  /// [getLegsForCycle] per cycle rather than losing each leg's own
  /// `contracts` to a repository-side sum.
  Future<List<WheelCycle>> getClosedCycles();

  /// Every cycle that is NOT closed — `sellingPuts` and `holdingShares`
  /// alike — across ALL underlyings, ordered by `startedAt` ascending
  /// (Pro Wave 2, D-22). The open-positions read path.
  ///
  /// Grouping [getAllLegs] by `cycleId` is deliberately NOT an acceptable
  /// substitute, and is the reason this method exists: a `holdingShares`
  /// cycle whose only call leg has been closed early has no open leg at
  /// all (Feature Invariant 16), yet its shares are still held and it still
  /// needs a row on the Today screen. Deriving the open set from open legs
  /// silently drops exactly that case — the D-P12 assignment case, which is
  /// the one the screen is most needed for.
  ///
  /// Ordering is by `startedAt` alone; ties (two cycles opened in the same
  /// millisecond) are unspecified beyond the set of cycles returned, so a
  /// caller that needs a stable render order must impose its own tie-break
  /// rather than rely on insertion order differing between implementations.
  Future<List<WheelCycle>> getOpenCycles();

  // --- Snapshot ---------------------------------------------------------

  /// Appends a new, immutable [Snapshot] reading for a leg. Snapshot
  /// history is append-only — this never overwrites a prior snapshot.
  Future<Snapshot> appendSnapshot(NewSnapshotInput snapshot);

  /// All snapshots for [legId], ordered by `takenAt` ascending.
  Future<List<Snapshot>> getSnapshotsForLeg(String legId);

  /// The most recently taken snapshot for [legId], or `null` if none has
  /// been recorded yet. Equivalent to the last element of
  /// [getSnapshotsForLeg], provided as its own method so Phase 4's
  /// positions list does not have to fetch a leg's entire snapshot history
  /// just to read the current one.
  Future<Snapshot?> getLatestSnapshotForLeg(String legId);

  // --- Roll / close / assignment (atomic, cycle-transitioning) --------

  /// Records a roll as ONE atomic two-write transaction (§3.3, Feature
  /// Invariant/S-024): closes [closingLegId] with `closeReason: rolled`
  /// and the given [closeDebitPerShare], and creates [newLeg] as the next
  /// leg in the same cycle (`sequence` and `rolledFromLegId` set by this
  /// method, not the caller). Never two calls the caller sequences.
  Future<({Leg closedLeg, Leg newLeg})> recordRoll({
    required String closingLegId,
    required Decimal closeDebitPerShare,
    Decimal? closeFee,
    required DateTime closedAt,
    required NewLegInput newLeg,
  });

  /// Closes a leg directly — NOT via a roll (`recordRoll`) and NOT via
  /// assignment (`recordAssignment`/`recordCallAway`); [reason] must be
  /// `closedEarly` or `expiredWorthless`.
  ///
  /// Also ends the owning cycle when [legId] is a `put` leg (Feature
  /// Invariant 16: `status -> closed`, `outcome` matching [reason],
  /// `endedAt -> closedAt`) — a cycle that never gets assigned still ends
  /// on the put side. Closing a `call` leg this way while the cycle is
  /// still `holdingShares` does NOT end the cycle (the shares are still
  /// held).
  Future<({Leg leg, WheelCycle cycle})> closeLeg({
    required String legId,
    required CloseReason reason,
    Decimal? closeDebitPerShare,
    Decimal? closeFee,
    required DateTime closedAt,
  });

  /// Records several legs as expired in ONE atomic write (D-13, S-217):
  /// either every leg in [legs] is closed or none is. Each leg is recorded
  /// exactly as `closeLeg` with `reason: expiredWorthless`,
  /// `closeDebitPerShare: Decimal.zero`, `closeFee: null` and the supplied
  /// `closedAt` records it — including the put-leg-ends-its-cycle rule, so
  /// a call leg on a cycle that is still `holdingShares` does not end that
  /// cycle.
  ///
  /// [legs] pairs each leg id with the `closedAt` to record for it; the
  /// caller supplies the expiration date per D-13's `recordedCloseDate`,
  /// never "now". Returns the closed legs in the order supplied.
  ///
  /// Throws [ArgumentError] — changing nothing — if [legs] is empty, if any
  /// id is unknown, or if any leg is already closed. Unlike [closeLeg] this
  /// method never silently re-closes a leg: the batch is a bulk action over
  /// a list the user selected, and a stale selection must fail loudly
  /// rather than rewrite history.
  Future<List<Leg>> markExpired({required List<({String legId, DateTime closedAt})> legs});

  /// Put-side assignment (§5.4, Feature Invariant 14): closes [legId]
  /// (`closeReason: assigned`), creates a [ShareLot] from [shareLot], and
  /// transitions the owning cycle to `holdingShares`. One atomic write.
  Future<({Leg leg, ShareLot shareLot, WheelCycle cycle})> recordAssignment({
    required String legId,
    Decimal? closeFee,
    required NewShareLotInput shareLot,
  });

  /// Call-side assignment / "called away" (Feature Invariant 14): closes
  /// the call [legId] (`closeReason: assigned`), consumes the cycle's
  /// [ShareLot] — the share position ends, so [getShareLotForCycle] stops
  /// returning it, but the row itself is **retained** as the cycle's
  /// assignment record ([getAssignmentForCycle], CR-1) — and ends the cycle
  /// (`status -> closed, outcome -> calledAway, endedAt -> closedAt`). One
  /// atomic write.
  Future<({Leg leg, WheelCycle cycle})> recordCallAway({
    required String legId,
    Decimal? closeFee,
    required DateTime closedAt,
  });

  // --- Leg metadata (non-lifecycle) -------------------------------------

  /// Updates mutable metadata on an already-persisted [Leg] that is NOT a
  /// lifecycle transition — contrast with [recordRoll], [closeLeg],
  /// [recordAssignment], and [recordCallAway], each of which also moves the
  /// leg from open to closed (or opens a new one). This method never
  /// changes `closedAt`, `closeReason`, `sequence`, `rolledFromLegId`,
  /// `openCreditPerShare`, `closeDebitPerShare`, `optionType`, `strike`,
  /// `expiration`, `contracts`, `openedAt`, `cycleId`, or
  /// `ruleProfileVersionId`,
  /// and never touches any cycle or [ShareLot] state — those fields remain
  /// exclusively owned by the lifecycle methods above.
  ///
  /// [acceptsAssignment] is editable regardless of lifecycle state (S-124
  /// edits it while the leg is still open). [openFee] and [closeFee] are
  /// likewise not gated on `closedAt` — an opening fee can be filled in
  /// after the fact just as a closing fee commonly is once a leg is
  /// already closed (S-122).
  ///
  /// **Null-vs-unchanged convention for [openFee]/[closeFee]**, recorded
  /// here because it is not inferable from the signature alone: `Decimal?`
  /// alone cannot distinguish "leave this fee as it is" from "set this fee
  /// to null," and null is a real, distinct state in this model — "not
  /// recorded" is deliberately different from "recorded as zero," which is
  /// the entire reason these columns are nullable (§4.3).
  /// - A `null` value with the matching `clear*` flag `false` (the
  ///   default) means *leave that fee unchanged*.
  /// - `clearOpenFee`/`clearCloseFee: true` means *reset that fee back to
  ///   `null`*. Passing both a non-null value and its `clear*` flag is a
  ///   contradictory call and throws [ArgumentError].
  ///
  /// Throws [ArgumentError] if the call would not change anything at all
  /// (`acceptsAssignment` is `null`, both fee values are `null`, and both
  /// `clear*` flags are `false`) — this method never silently no-ops.
  Future<Leg> updateLegMetadata({
    required String legId,
    bool? acceptsAssignment,
    Decimal? openFee,
    Decimal? closeFee,
    bool clearOpenFee = false,
    bool clearCloseFee = false,
  });

  // --- ShareLot ---------------------------------------------------------

  /// The **active** share lot for [cycleId] — the one backing a currently
  /// `holdingShares` cycle — or `null` if the cycle has none (not yet
  /// assigned, or already called away). A cycle holds at most one live
  /// [ShareLot] at a time. For the cycle's assignment record after it has
  /// closed, use [getAssignmentForCycle].
  Future<ShareLot?> getShareLotForCycle(String cycleId);

  /// The [ShareLot] this cycle's put-side assignment created, retained for
  /// the cycle's whole life **and after it closes** (CR-1) — unlike
  /// [getShareLotForCycle], this does not stop returning it at call-away.
  /// `null` for a cycle that never reached a put-side assignment, and for a
  /// cycle closed before the record was retained.
  ///
  /// [ShareLot.assignmentStrike] and [ShareLot.contracts] are the values
  /// actually recorded at assignment, which the assigned leg's own
  /// `strike`/`contracts` do not necessarily match (both are user-entered).
  /// Any closed-cycle figure derived from the assignment — starting with
  /// `peakCapitalCommitted`, and therefore return on capital — must be
  /// computed from this record rather than reconstructed from the leg.
  Future<ShareLot?> getAssignmentForCycle(String cycleId);

  // --- UserPreferences (Iteration 3, schema v2) --------------------------

  /// The single global [UserPreferencesData] row (Feature Invariants 21,
  /// 24). Always resolves — seeded at migration/construction time — never
  /// null.
  Future<UserPreferencesData> getPreferences();

  /// Persists [prefs] as the new single global preferences row and returns
  /// it back.
  Future<UserPreferencesData> updatePreferences(UserPreferencesData prefs);

  // --- Entitlement cache (Pro Wave 2, schema v6, D-25) --------------------

  /// The single global [EntitlementCacheData] row — what the last
  /// successful store read reported. Always resolves: seeded at
  /// migration/construction time, never null, so the state layer never has
  /// to distinguish "no row" from "no entitlement" (D-26). A fresh install
  /// resolves to the free tier's `EntitlementCacheDefaults` — inactive with
  /// a null `checkedAt`, i.e. `unknown`, NOT a cached "no".
  ///
  /// Store-derived state, deliberately outside the export envelope: this
  /// row is written only by a successful store read and is never carried in
  /// [exportToJson] nor touched by [restoreFromJson] (S-257). A hand-edited
  /// backup must not be able to grant Pro, and restoring an old ledger must
  /// not revoke it.
  Future<EntitlementCacheData> getEntitlementCache();

  /// Replaces the single [EntitlementCacheData] row in place and returns it
  /// back — never appends a second row (S-256), and never called with a
  /// partial result: a failed store read must leave the previous successful
  /// read intact rather than overwrite it with `unknown` (D-26).
  Future<EntitlementCacheData> saveEntitlementCache(EntitlementCacheData cache);

  // --- Export / import (Phase 19, `docs/brief-ledger.md` §5) -------------

  /// Full JSON export of every table -- every [Underlying], [WheelCycle],
  /// [Leg] (fees/`acceptsAssignment` included), [Snapshot], [ShareLot],
  /// [RuleProfileData] and every [RuleProfileVersionData], and the single
  /// [UserPreferencesData] row. Returns a
  /// plain `String`; the envelope shape lives in
  /// `lib/data/export/ledger_export.dart`'s `LedgerExport`, which is also
  /// the only place the matching [restoreFromJson] parses/validates a
  /// file -- nothing storage-specific (no Drift type, no file path) ever
  /// appears here.
  Future<String> exportToJson();

  /// The number of [WheelCycle] rows currently persisted -- the exact count
  /// an import confirmation dialog names before [restoreFromJson] destroys
  /// them (S-151). A pure read; never mutates anything.
  Future<int> countCyclesForReplace();

  /// Replace-all restore (§5: "Do not build merge in this iteration").
  /// Every table is wiped and replaced with [json]'s contents as a single
  /// atomic operation -- either every row lands, or (on any validation
  /// failure) none does. [json] is parsed and hard-validated in full
  /// (`LedgerExport.fromJsonString`) *before* anything is written, so a
  /// malformed file throws `LedgerImportFormatException` and leaves every
  /// existing row completely untouched (S-152) -- it is never possible to
  /// observe a partially-applied import.
  ///
  /// Accepts export `formatVersion` 2 (current) and 1 (everything the app
  /// exported before Iteration 5): a format-1 file is converted in memory
  /// by `LedgerExport` first -- each profile's inline values become its v1
  /// version row, `effectiveAt` = [now] (optional so tests can pin it; the
  /// UI passes nothing and means "the import moment"), and every leg's
  /// `ruleProfileId` is rewritten to `<value>-v1` (D-8).
  Future<void> restoreFromJson(String json, {DateTime? now});
}

/// Caller-supplied fields for a new [Leg]. `id`, `cycleId`, `sequence`, and
/// `rolledFromLegId` are always assigned by the repository — never by the
/// caller — because they depend on write-time context (a newly created
/// cycle id, or the position of this leg in an existing roll chain) that
/// only the repository has at the moment of the write.
@freezed
abstract class NewLegInput with _$NewLegInput {
  const factory NewLegInput({
    required OptionType optionType,
    required Decimal strike,
    required DateTime expiration,
    required int contracts,
    required DateTime openedAt,
    required Decimal openCreditPerShare,

    /// The `rule_profile_version` id this leg pins
    /// (`<profileId>-v<n>`, see [Leg.ruleProfileVersionId]) — always a
    /// version id, never a bare profile id, so the leg's rules are truthful
    /// to the moment it opened even after later edits.
    required String ruleProfileVersionId,
    double? ivAtOpen,
    double? ivRankAtOpen,
    double? deltaAtOpen,
    Decimal? underlyingPriceAtOpen,

    /// Total fee for opening this leg, in dollars — `null` means "not
    /// recorded," never zero (Phase 15). Carried straight onto the created
    /// [Leg].
    Decimal? openFee,

    /// Whether this leg's owner accepts assignment rather than rolling
    /// (Phase 15/16 Gate 2). Defaults to `true` when the caller doesn't
    /// pass one (S-094); an explicit value (e.g. `false`, inherited across
    /// a roll per S-095/S-102) is never overwritten by the repository.
    @Default(true) bool acceptsAssignment,
  }) = _NewLegInput;
}

/// Caller-supplied threshold values for a new [RuleProfileVersionData]
/// version. `id`, `version`, `profileId`, and `effectiveAt` are NOT here —
/// the id and version are derived by `appendRuleProfileVersion`, and the
/// profile id / timestamp are that method's own parameters.
@freezed
abstract class NewRuleProfileVersionInput with _$NewRuleProfileVersionInput {
  const factory NewRuleProfileVersionInput({
    required double profitTargetPct,
    required double assignThreshold,
    required double baseRollBand,
    required double midIvRollBand,
    required double highIvRollBand,
    required double midIvCutoff,
    required double highIvCutoff,
    required int tailDteDays,
    required Decimal tailExtrinsicThreshold,
    required double minIvRank,
    required double minAnnualisedYield,
    required int targetDteMin,
    required int targetDteMax,
    required double targetDelta,
  }) = _NewRuleProfileVersionInput;
}

/// Caller-supplied fields for a new [Snapshot]. `id` is assigned by the
/// repository.
@freezed
abstract class NewSnapshotInput with _$NewSnapshotInput {
  const factory NewSnapshotInput({
    required String legId,
    required DateTime takenAt,
    required Decimal optionMark,
    required Decimal underlyingPrice,
    required double deltaAsEntered,
    required DeltaConvention deltaConvention,
    double? gamma,
    double? theta,
    double? vega,
    double? iv,
    int? openInterest,
    int? volume,
  }) = _NewSnapshotInput;
}

/// Caller-supplied fields for a new [ShareLot]. `id` and `cycleId` are
/// assigned by the repository (`cycleId` is derived from the leg being
/// assigned in `recordAssignment`).
@freezed
abstract class NewShareLotInput with _$NewShareLotInput {
  const factory NewShareLotInput({
    required DateTime assignedAt,
    required Decimal assignmentStrike,
    required int contracts,
  }) = _NewShareLotInput;
}
